config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, :controllers => {
  #                      :registrations => "users/registrations",
  #                      :sessions => "users/sessions",
  #                    }

  # devise_scope :user do
  #   get "user/:id", :to => "users/registrations#detail"
  #   get "signup", :to => "users/registrations#new"
  #   get "login", :to => "users/sessions#new"
  #   get "logout", :to => "users/sessions#destroy"
  # end

  # get "route", to: "route#new"
  # post "route/show", to: "route#show"

  resources :driving do
    collection do
      get :list
    end
  end
  root to: redirect('/driving')
end

app/controllers/driving_controller.rb
class DrivingController < ApplicationController
  def index
    p "index start"
  end

  def list
    p "list start"
    p "params[:src]:" + params[:src]
    if params[:src].present?
      # cash確認
      srcGeoCashEntity = SrcGeoCash.find_by(place_name: params[:src])
      if srcGeoCashEntity.nil?
        geoReq = Api::GoogleGeo::Request.new
        geoRes = geoReq.request(params[:src])
        SrcGeoCash.create(
          place_name: params[:src],
          latitude: geoRes["result"]["latitude"],
          longitude: geoRes["result"]["longitude"],
        )
      else
        p "geocash found"
        geoRes = { "result" => { "latitude" => srcGeoCashEntity.latitude, "longitude" => srcGeoCashEntity.longitude } }
      end

      routeRequest = Api::GoogleRoute::Request.new
      route = []
      randomList = []
      @result = []
      @srcdestMap = {}
      Tourist.all.each do |s|
        distance = Tourist.distance(geoRes["result"]["latitude"], geoRes["result"]["longitude"], s["latitude"].to_f,
                                    s["longitude"].to_f)
        if distance < 100
          randomList.push({ src: params[:src], dest: s["latitude"] + "," + s["longitude"], place_name: s["place_name"] })
        end
      end
      if !randomList.empty?
        @srcdestMap = randomList.sample
        # cash確認
        routeCashEntity = RouteCash.find_by(src: @srcdestMap[:src], dest: @srcdestMap[:dest])
        if routeCashEntity.nil?
          route.push(@srcdestMap)
          routeRes = routeRequest.request(route)
          RouteCash.create(
            src: geoRes["result"]["latitude"].to_s + "," + geoRes["result"]["longitude"].to_s,
            dest: @srcdestMap[:dest],
            highway: routeRes["result"][0]["distance"]["highway"],
            localway: routeRes["result"][0]["distance"]["localway"],
          )
        else
          p "geocash found"
          routeRes = { "result" => { "location" => { "src" => @srcdestMap[:src], "dest" => @srcdestMap[:dest] }, "distance" => { "highway" => routeCashEntity.highway, "localway" => routeCashEntity.localway } } }
        end

        # 返却した値はそのまま画面へ
        @result = routeRes["result"]
      end

      render :list
    else
      redirect_to action: :index
    end
  end
end

app/views/driving/confirm.html.erb
confirm

app/views/driving/index.html.erb
<%= form_with(url: list_driving_index_path, local: true, id: "new-event", method: 'get') do |f| %>
  <div class="mb-5 display-1 kiwi_font">
    週末どこ行く？
  </div>
  <div class="input-group col-md-auto mb-3">
    <span class="input-group-text kiwi_font" id="basic-addon1">出発地</span>
    <%= f.text_field :src, value: @src, class:"form-control col-xl", placeholder: "名称、座標どちらでも可" %>
    <button class="btn btn-primary kiwi_font" type="button" id="geoBtn">現在地取得</button>
  </div>
  <div class="d-grid gap-2 col-6 mx-auto">
    <%= f.submit "出発", class: "kiwi_font btn btn-primary", name: nil %>
  </div>
<% end %>
<script>
  $('#geoBtn').on('click', function() {
    navigator.geolocation.getCurrentPosition(function(pos){
      $("#src").val(pos.coords.latitude + "," + pos.coords.longitude)
    },function(){

    });
  });
</script>

app/views/driving/list.html.erb
<%= link_to("戻る", driving_index_path) %>
<h2 class="kiwi_font">往復で100kmくらいの観光地</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">出発地</th>
      <th scope="col">到着地</th>
      <th scope="col">高速での距離(km)</th>
      <th scope="col">下道での距離(km)</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%@result.each do |s|%>
      <tr>
        <td><%= s["location"]["src"] %></th>
        <td><%= @srcdestMap[:place_name] %></td>
        <td><%= s["distance"]["highway"] %></td>
        <td><%= s["distance"]["localway"] %></td>
        <td><%= link_to("行く", "https://www.google.co.jp/maps/dir/" + s["location"]["src"] +"/" + s["location"]["dest"] + "/data=!4m3!4m2!3e0!4e0", target: :_blank, rel: "noopener noreferrer") %></td>
      </tr>
    <%end%>
  </tbody>
</table>